### ISSUE TITLE
OptionalBinding initializer crashes

### ISSUE THREAD

**Issue by conrodi** [AlanQuatermain/AQUI#1]
The first form of the optional binding, as in
`TextField("Name", text: Binding($thing.name, ""))`,
crashes for me if the attribute,`thing.name`, truly is nil. This happens if a Core Data string attribute is not otherwise initialized. The crash that happens at
` self.init(source)!`
is
`Fatal error: Unexpectedly found nil while unwrapping an Optional value`.

Two workarounds:
(1) Initialize the attribute to something.
(2) Use the other form of optional binding as in
`TextField(text: Binding($name, replacingWithNil: ""))`

Maybe I don't really understand the distinction between the two use cases, but it still seems the
binding without `replacingWithNil:` should not result in a fatal error despite misuse.

**Comment by AlanQuatermain** [comment]
That’s strange. The code should be checking whether the value is nil and explicitly assigning it to the given default. I’ll have to take a look at this when I get home this afternoon. Is the optional value a regular optional or an implicitly unwrapped one? It may be that the method I’m using to test for nil is causing an IUO to be unwrapped, and there might be a better way.

**Comment by conrodi** [comment]
It happens for a Core Data attribute of type String that is never initialized or otherwise perturbed before it’s used in the Binding initializer. 

The other optional binding initializer seems to work fine. 

CR

**Comment by AlanQuatermain** [comment]
Well, this is an interesting one. In unit tests, I can get neither an `@Binding` or an `@State` variable to accept a new value *at all*. Ultimately that's what's causing the crash: assigning a new value via `binding.wrappedValue = something` just doesn't actually have any effect. I suspect that there's some part of the SwiftUI view lifecycle that actually wires them up properly, such that they can only be used after being 'rendered' somewhere. Simply creating one and updating its `wrappedValue` does nothing unless you're using a manual get/set targeting something else that you know is modifiable already (like a local `var` declaration). That this also applies for `@State` variables suggests that there's something special in the `LocationBox<>` type that hasn't been initialized or otherwise set up.

I've tried a couple of tricks to delay the initial assignment of the wrapped value, but I'm not seeing it work just yet, which is rather annoying.

**Comment by AlanQuatermain** [comment]
The crash no longer occurs, but there are potential side-effects: if the getter is called early, before the write is enabled, then the default value won't be set on the underlying binding. Later gets will fix this, if they're not elided by SwiftUI's update algorithms, but there remains a possibility that the underlying data will remain `nil`.
